name: AllayChat
version: '${version}'
main: net.voxelarc.allaychat.AllayChatPlugin
loader: net.voxelarc.allaychat.AllayChatLoader
api-version: '1.21'
folia-supported: true

authors:
  - hyperion

dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: true
    PlaceholderAPI:
      load: BEFORE
      required: true
    LiteBans:
      load: BEFORE
      required: false